# https://www.netlify.com/docs/netlify-toml-reference/
[Settings]
[build]
  publish = "build/"
  command = "npm run init; gulp svg; gulp all"

[context.production]
  command = "npm run init; gulp svg; gulp all -p"
